#!/usr/bin/env bash
# -*-coding:utf-8 -*-
# -------------------------------------------------------------------------
# Path          - /usr/bin/proctl
# Git           - https://github.com/The-Repo-Club/
# Author        - The-Repo-Club [wayne6324@gmail.com]
# Start On      - Sun 20 February 2022, 11:46:45 am (GMT)
# Modified On   - Sun 20 February 2022, 11:46:47 am (GMT) 
# -------------------------------------------------------------------------
