.TH "PROCTL" "1" "VERSION" "PROCTL" "VERSION"
.hy
.SH NAME
.PP
proctl \[en] Github Project Manager
.SH DESCRIPTION
.PP
\f[B]proctl\f[R] is a tool that can manage, switch between templated licenses, and set languages.
.SH GENERAL OPTIONS
.TP
\fB\-initialize\fR      \fB\-i\fR @project_name
initialize a git repo for a project
.TP
\fB\-list\-licenses\fR   \fB\-l\fR
list available licenses
.TP
\fB\-list\-languages\fR  \fB\-ll\fR
list available languages
.TP
\fB\-current\-license\fR \fB\-c\fR
show current active project license
.TP
\fB\-pick\-license\fR    \fB\-p\fR
pick a license in a FZF menu
.TP
\fB\-pick\-language\fR   \fB\-pl\fR
pick a language in a FZF menu
.TP
\fB\-preview\-license\fR \fB\-P\fR @license_name
preview a license template
.TP
\fB\-remove\-license\fR  \fB\-r\fR
remove all licenses from the current project
.TP
\fB\-search\-license\fR  \fB\-s\fR '<query | patten>'
search for license
.TP
\fB\-template\-help\fR   \fB\-T\fR
print help for templating
.TP
\fB\-new\-template\fR    \fB\-t\fR
create a new license template
.TP
\fB\-delete\-license\fR  \fB\-R\fR @license_name ...
delete a license from templates
.TP
\fB\-new\-config\fR      \fB\-C\fR
create a default config overwriting current one
.TP
\fB\-check\-conflict\fR  \fB\-k\fR
check if current licene(s) are conflicting
.TP
\fB\-help\fR            \fB\-h\fR
show this helpful list of commands
.SH AUTHORS
HeCodes2Much.
